language: csharp

mono: none
dotnet: 3.1.101

before_install:
    - sudo apt-get install nuget
    - sudo apt-get install graphviz

install:
<<<<<<< HEAD
    - nuget restore hw2/CsharpTasks/CsharpTasks.sln
    - nuget restore hw2/FsharpTasks/FsharpTasks.sln

script:
    - dotnet test hw2/CsharpTasks/CsharpTasks.sln
    - dotnet test hw2/FsharpTasks/FsharpTasks.sln
=======
    - nuget restore hw1/Tasks/Tasks.sln

script:
    - dotnet build hw1/Tasks/Tasks.sln
    - dotnet test hw1/Tasks/Tasks.sln
>>>>>>> master
