language: csharp

mono: none
dotnet: 3.1.101

before_install:
    - sudo apt-get install nuget

install:
    - nuget restore hw2/CsharpTasks/CsharpTasks.sln
    - nuget restore hw2/FsharpTasks/FsharpTasks.sln
    - nuget restore hw3/FsharpTasks/FsharpTasks.sln

script:
    - dotnet build hw2/CsharpTasks/CsharpTasks.sln
    - dotnet build hw2/FsharpTasks/FsharpTasks.sln
    - dotnet test hw3/FsharpTasks/FsharpTasks.sln